# SPDX-FileCopyrightText: 2023 Sergio Durigan Junior
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Ensure Roundcube paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: "{{ roundcube_uid }}"
    group: "{{ roundcube_gid }}"
  with_items:
    - "{{ roundcube_base_path }}"
    - "{{ roundcube_config_path }}"
    - "{{ roundcube_sqlite_db_path }}"
    - "{{ roundcube_tmp_path }}"

- name: Ensure Roundcube path for HTML assets exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0751" # This ensures to avoid "unable to check htaccess file, ensure it is readable and that '/var/www/html/' is executable" error
    owner: "{{ roundcube_uid }}"
    group: "{{ roundcube_gid }}"
  with_items:
    - "{{ roundcube_html_path }}"

- name: Ensure Roundcube support files installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ roundcube_base_path }}/{{ item }}"
    mode: "0640"
    owner: "{{ roundcube_uid }}"
    group: "{{ roundcube_gid }}"
  with_items:
    - env
    - labels
  register: roundcube_support_files_result

- name: Ensure Roundcube container image is pulled via community.docker.docker_image
  when: devture_systemd_docker_base_container_image_pull_method == 'ansible-module'
  community.docker.docker_image:
    name: "{{ roundcube_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ roundcube_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else roundcube_container_image_force_pull }}"
  register: roundcube_container_image_pull_result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: roundcube_container_image_pull_result is not failed

- name: Ensure Roundcube container image is pulled via ansible.builtin.command
  when: devture_systemd_docker_base_container_image_pull_method == 'command'
  ansible.builtin.command:
    cmd: "{{ devture_systemd_docker_base_host_command_docker }} pull {{ roundcube_container_image }}"
  register: roundcube_container_image_pull_result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: roundcube_container_image_pull_result is not failed
  changed_when: "'Downloaded newer image' in roundcube_container_image_pull_result.stdout"

- name: Ensure Roundcube container network is created via community.docker.docker_network
  when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
  community.docker.docker_network:
    enable_ipv6: "{{ devture_systemd_docker_base_ipv6_enabled }}"
    name: "{{ roundcube_container_network }}"
    driver: bridge
    driver_options: "{{ devture_systemd_docker_base_container_networks_driver_options }}"
  register: roundcube_network_creation_result

- name: Ensure Roundcube container network is created via ansible.builtin.command
  when: devture_systemd_docker_base_container_network_creation_method == 'command'
  ansible.builtin.command:
    cmd: >-
      {{ devture_systemd_docker_base_host_command_docker }} network create
      {% if devture_systemd_docker_base_ipv6_enabled %}--ipv6{% endif %}
      {{ devture_systemd_docker_base_container_networks_driver_options_string }}
      {{ roundcube_container_network }}
  register: roundcube_network_creation_result
  changed_when: roundcube_network_creation_result.rc == 0
  failed_when: roundcube_network_creation_result.rc != 0 and 'already exists' not in roundcube_network_creation_result.stderr

- name: Ensure Roundcube systemd service is present
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/roundcube.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ roundcube_identifier }}.service"
    mode: "0644"
  register: roundcube_systemd_service_result

- name: Determine whether Roundcube needs a restart
  ansible.builtin.set_fact:
    roundcube_restart_necessary: >-
      {{
        roundcube_support_files_result.changed | default(false)
        or roundcube_systemd_service_result.changed | default(false)
        or roundcube_container_image_pull_result.changed | default(false)
      }}
